const tasks = [
  {
    id: 1,
    task: "today",
    slug: "sleep-early",
    detail: "i have to",
    priorty: "",
    date: new Date("2021-06-22"),
    done: true,
    deadline: "2021-07-02",
    history: "today",
  },
  {
    id: 2,
    task: "future",
    slug: "solve-project",
    detail: "mamamia",
    date: new Date("2021-06-23"),
    done: true,
    deadline: "2021-06-29",
    history: "today",
  },
  {
    id: 3,
    task: "today",
    slug: "wake-up",
    detail: "wake up not sleepy",
    date: new Date("2021-06-22"),
    done: false,
    deadline: "",
    history: "future",
  },
  {
    id: 4,
    task: "future",
    slug: "sleep-again",
    detail: "not neccessery",
    date: new Date("2021-06-20"),
    done: false,
    deadline: "",
    history: "future",
  },
];
export default tasks;
